name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on Multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Xcode on macOS
      - name: Set up Xcode (macOS only)
        if: runner.os == 'macOS'
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      # Step 3: Install dependencies (Swift)
      - name: Install dependencies
        run: |
          swift package resolve

      # Step 4: Run tests
      - name: Run Tests
        run: |
          swift test --enable-code-coverage
