name: New

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on macOS
    runs-on: macos-latest
    steps:
    # Step 0: Set up Xcode
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0'

      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Confirm Xcode version
        run: xcodebuild -list
        

      # Step 5: Run tests
      - name: Run tests
        run: xcodebuild test -scheme "AppFoundationsOfComputerScience" -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' -enableCodeCoverage YES





