name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on macOS
    runs-on: macos-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Xcode
      - name: Set Xcode version to 16.1
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer

      - name: Confirm Xcode version
        run: xcodebuild -version

      # Step 4: Reset simulators (optional)
      - name: Reset iOS Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      # Step 5: Run tests with timeout

      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

      # Step 6: Upload coverage data
      - name: Upload Coverage Report
        if: success() || failure()
        run: |
          bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN





