name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on macOS
    runs-on: macos-15
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Xcode
      - name: Set Xcode version to 16.1
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer

      - name: Confirm Xcode version
        run: xcodebuild -version

      # Step 4: Reset simulators (optional)
      - name: Reset iOS Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      # Step 5: Run tests with timeout
      - name: Build and Test
        run: xcodebuild clean build test -project AppFoundationsOfComputerScience/AppFoundationsOfComputerScience.xcodeproj -scheme AppFoundationsOfComputerScienceTests -destination 'platform:visionOS Simulator, variant:Designed for [iPad,iPhone], id:CE1D6CAA-665F-41DE-A166-BF4B73A351C2, OS:2.0, name:Apple Vision Pro' -enableCodeCoverage YES

      # Step 6: Upload coverage data
      - name: Upload Coverage Report
        if: success() || failure()
        run: |
          bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN





