name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Instala o Rosetta (caso necessário)
      - name: Install Rosetta
        run: sudo softwareupdate --install-rosetta --agree-to-license

      # Configura o Xcode para usar a versão 16.1
      - name: Set Xcode version to 16.1
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer

      # Verifica a versão do Xcode
      - name: Confirm Xcode version
        run: xcodebuild -version

      # Run tests
      - name: Run tests
        run: xcodebuild test -project AppFoundationsOfComputerScience/AppFoundationsOfComputerScience.xcodeproj -scheme AppFoundationsOfComputerScience -destination 'platform=iOS Simulator,name=iPhone 15'




