name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-xcode:
    runs-on: macos-latest
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version
