name: Swift Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Xcode 16.2
        run: sudo softwareupdate --install-rosetta --agree-to-license

      # Select the latest available Xcode version
      - name: Select available Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer

      # Run tests
      - name: Run tests
        run: xcodebuild test -project AppFoundationsOfComputerScience/AppFoundationsOfComputerScience.xcodeproj -scheme AppFoundationsOfComputerScience -destination 'platform=iOS Simulator,name=iPhone 14'

